spring:
   profiles:
      active: mysql
   batch:
      job:
         names: ${job.name:NONE}
#         enabled: false
---
spring:
   config:
      activate:
         on-profile: local
   datasource:
      hikari:
         jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
         username: sa
         password:
         driver-class-name: org.h2.Driver
   batch:
      jdbc:
         initialize-schema: embedded
      job:
         enabled: false
---
spring:
   config:
      activate:
         on-profile: mysql
   datasource:
      hikari:
         jdbc-url: jdbc:log4jdbc:mysql://localhost:12345/springbatch?useUnicode=true&characterEncoding=utf8
         username: root
         password: root
         driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
   batch:
      jdbc:
         initialize-schema: always
server:
   port: 8090